aggregator:
  settings:
    best_state_path: save/keras_cnn_cifar_best.pbuf
    db_store_rounds: 2
    init_state_path: save/keras_cnn_cifar_init.pbuf
    last_state_path: save/keras_cnn_cifar_last.pbuf
    rounds_to_train: 10
    write_logs: true
  template: openfl.component.Aggregator
assigner:
  settings:
    task_groups:
    - name: train_and_validate
      percentage: 1.0
      tasks:
      - aggregated_model_validation
      - train
      - locally_tuned_model_validation
  template: openfl.component.RandomGroupedAssigner
collaborator:
  settings:
    db_store_rounds: 1
    delta_updates: false
    opt_treatment: RESET
  template: openfl.component.Collaborator
compression_pipeline:
  settings: {}
  template: openfl.pipelines.NoCompressionPipeline
data_loader:
  settings:
    batch_size: 256
    collaborator_count: 2
    data_group_name: cifar
  template: src.tfcifar_inmemory.TensorFlowCIFARInMemory
network:
  settings:
    agg_addr: localhost
    agg_port: 60413
    cert_folder: cert
    client_reconnect_interval: 5
    disable_client_auth: false
    hash_salt: auto
    tls: true
  template: openfl.federation.Network
task_runner:
  settings: {}
  template: src.keras_cnn.KerasCNN
tasks:
  aggregated_model_validation:
    function: validate
    kwargs:
      apply: global
      batch_size: 32
      metrics:
      - accuracy
  locally_tuned_model_validation:
    function: validate
    kwargs:
      apply: local
      batch_size: 32
      metrics:
      - accuracy
  settings: {}
  train:
    function: train
    kwargs:
      batch_size: 32
      epochs: 1
      metrics:
      - loss
